markdown: redcarpet
highlighter: pygments
kramdown:
  input: GFM

gems:
  - jekyll-sitemap

exclude: [Vagrantfile]

paginate: 5

title: Herman J. Radtke III Blog
url: http://hermanradtke.com
author:
 name: Herman J. Radtke III
 email: herman@hermanradtke.com
baseurl: /
blog: "<a href='/'>blog</a>"
feed: "<a href='/atom.xml'>atom feed</a>"
projects:
 -
  name: mob
  link: https://github.com/hjr3/mob
  description: "A multi-echo server built on mio."
 -
  name: hal-rs
  link: https://github.com/hjr3/hal-rs
  description: "A pure rust library for generating Hal responses."
 -
  name: hal-rs-demo
  link: https://github.com/hjr3/hal-rs-demo
  description: "A demo web server for the hal-rs library."
