markdown: kramdown

kramdown:
  input: GFM

exclude: [Vagrantfile, vendor]

title: Herman J. Radtke III Blog
name: Herman J. Radtke III Blog
url: http://hermanradtke.com
author:
 name: Herman J. Radtke III
 email: herman@hermanradtke.com

blog: "<a href='/'>blog</a>"
atom_feed: "<a href='/'>blog</a>"

feed:
  path: atom.xml

projects:
 -
  name: mob
  link: https://github.com/hjr3/mob
  description: "A multi-echo server built on mio."
 -
  name: hal-rs
  link: https://github.com/hjr3/hal-rs
  description: "A pure rust library for generating Hal responses."
 -
  name: selecta-score-rs
  link: https://github.com/hjr3/selecta-score-rs
  description: "A more performant version of the selecta scoring algorithm."
 -
  name: softnet-stat
  link: https://github.com/hjr3/softnet-stat
  description: "Parse the `/proc/net/softnet_stat` file into something more readable."

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
